### ISSUE TITLE
Consider storing data in zenodo rather than cloud storage

### ISSUE THREAD

**Issue by seandavi** [shbrief/OmicsMLRepoR#33]
https://github.com/shbrief/OmicsMLRepoR/blob/f66acbb3e09ec7668a8125fecc8c8eafc7e9272b/R/getMetadata.R#L62

Note that using Google Cloud Storage will result in egress charges. It isn't a big deal for such small files unless someone does something like run a download in a loop (inadvertently). Using Zenodo instead 1) allows clearer versioning and 2) avoids egress charges, and 3) gets you a DOI for the data.

**Comment by shbrief** [comment]
d3dc2ed04baf918869b054b54471aa564185beeb
